version: 2.1

aliases:
  - &restore-node-modules-cache
    name: Restore node_modules cache
    key: v1-npm-deps-{{ checksum "package-lock.json" }}

  - &save-npm-cache
    name: Save npm cache
    paths:
      - ~/.cache/npm
    key: v1-npm-cache

  - &save-node-modules-cache
    name: Save node_modules cache
    paths:
      - node_modules
    key: v1-npm-deps-{{ checksum "package-lock.json" }}

defaults: &defaults
  docker:
    - image: node:16.6.0-stretch-slim
  working_directory: ~/caffeine

jobs:
  build_packages:
    <<: *defaults

    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache

      - run:
          name: Install Dependencies
          command: npm install --frozen-lockfile

      - run:
          name: Build Packages
          command: npm run build

      - save_cache: *save-node-modules-cache
      - save_cache: *save-npm-cache
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'

  lint_test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/caffeine

      - run:
          name: Run Lint
          command: npm run lint

  unit_test_ui:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/caffeine

      - run:
          name: Run Unit Tests
          command: npm run test:ci:ui

  # unit_test_backend:
  #   <<: *defaults

  #   steps:
  #     - attach_workspace:
  #         at: ~/caffeine

  #     - run:
  #         name: Run Unit Tests
  #         command: npm run test:ci:api

workflows:
  version: 2

  branch-workflow:
    jobs:
      - build_packages
      - lint_test:
          requires:
            - build_packages
      - unit_test_ui:
          requires:
            - build_packages
      # - unit_test_backend:
      #     requires:
      #       - build_packages
